# Generated by Django 5.1.11 on 2025-09-26 11:59

import django.core.validators
import utilities.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Display name for this playlist (shown to users).', max_length=255, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Short summary shown in the app or SEO snippets.', null=True, verbose_name='Description')),
                ('playlist_type', models.CharField(blank=True, choices=[('MEDITATION_SERIES', 'Meditation Series'), ('BREATHWORK_SERIES', 'Breathwork Series'), ('MINDFULNESS', 'Mindfulness Practices'), ('ZEN_MODE', 'Zen Mode Exclusives'), ('SLEEP_WELLNESS', 'Sleep & Relaxation'), ('STRESS_RELIEF', 'Stress Relief'), ('WEIGHT_MANAGEMENT', 'Weight Management'), ('FLEXIBILITY', 'Flexibility & Mobility'), ('STRENGTH', 'Strength Building'), ('ENERGY_BOOST', 'Energy Boost'), ('FOCUS_CONCENTRATION', 'Focus & Concentration'), ('ANXIETY_RELIEF', 'Anxiety Relief'), ('EMOTIONAL_BALANCE', 'Emotional Balance'), ('DETOX_CLEANSE', 'Detox & Cleanse'), ('IMMUNITY_SUPPORT', 'Immunity Support'), ('DAILY_CHALLENGE', 'Daily Challenge'), ('WEEKLY_PROGRAM', 'Weekly Program'), ('MONTHLY_JOURNEY', 'Monthly Journey'), ('QUICK_SESSIONS', 'Quick 5–10 min Sessions'), ('LONG_FORM_RETREAT', 'Long-form Retreat'), ('PRENATAL', 'Prenatal Yoga'), ('POSTNATAL', 'Postnatal Yoga'), ('KIDS', 'Kids Yoga & Mindfulness'), ('SENIORS', 'Senior Wellness'), ('OFFICE_BREAK', 'Office/Workplace Break'), ('TRAVEL_FRIENDLY', 'Travel-Friendly Routines'), ('TRADITIONAL_HATHA', 'Traditional Hatha Yoga'), ('VINYASA_FLOW', 'Vinyasa Flow'), ('ASHTANGA', 'Ashtanga Series'), ('BHAKTI_DEVOTIONAL', 'Bhakti/Devotional'), ('SUTRAS_MANTRAS', 'Sutras & Mantras')], help_text='Select the category/genre of this playlist.', max_length=50, null=True, verbose_name='Playlist Type')),
                ('language', models.CharField(blank=True, choices=[('ENGLISH', 'English'), ('SPANISH', 'Spanish'), ('FRENCH', 'French'), ('GERMAN', 'German'), ('ITALIAN', 'Italian'), ('PORTUGUESE', 'Portuguese'), ('RUSSIAN', 'Russian'), ('CHINESE_SIMPLIFIED', 'Chinese (Simplified)'), ('CHINESE_TRADITIONAL', 'Chinese (Traditional)'), ('JAPANESE', 'Japanese'), ('KOREAN', 'Korean'), ('ARABIC', 'Arabic'), ('TURKISH', 'Turkish'), ('DUTCH', 'Dutch'), ('SWEDISH', 'Swedish'), ('NORWEGIAN', 'Norwegian'), ('DANISH', 'Danish'), ('GREEK', 'Greek'), ('HEBREW', 'Hebrew'), ('POLISH', 'Polish'), ('UKRAINIAN', 'Ukrainian'), ('THAI', 'Thai'), ('VIETNAMESE', 'Vietnamese'), ('INDONESIAN', 'Indonesian'), ('MALAY', 'Malay'), ('FILIPINO', 'Filipino'), ('HINDI', 'Hindi'), ('BENGALI', 'Bengali'), ('PUNJABI', 'Punjabi'), ('MARATHI', 'Marathi'), ('GUJARATI', 'Gujarati'), ('TAMIL', 'Tamil'), ('TELUGU', 'Telugu'), ('KANNADA', 'Kannada'), ('MALAYALAM', 'Malayalam'), ('ODIA', 'Odia'), ('ASSAMESE', 'Assamese'), ('URDU', 'Urdu'), ('SANSKRIT', 'Sanskrit')], help_text='Select the main language of this playlist.', max_length=50, null=True, verbose_name='Language')),
                ('thumbnail', models.ImageField(blank=True, help_text='Cover image for this playlist, shown in feeds and listings.', max_length=1000, null=True, storage=utilities.storages.ImageKitStorage(), upload_to='content/playlists/thumbnails', verbose_name='Thumbnail')),
                ('thumbnail_file_id', models.CharField(blank=True, editable=False, max_length=1000, null=True, verbose_name='Thumbnail File ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('impressions', models.PositiveBigIntegerField(default=0, help_text='Times shown in feeds/search.')),
                ('clicks', models.PositiveBigIntegerField(default=0, help_text='Times opened from an impression.')),
                ('starts', models.PositiveBigIntegerField(default=0, help_text='First play started (at least 1s).')),
                ('completes', models.PositiveBigIntegerField(default=0, help_text='Completed all items or 90% avg.')),
                ('likes', models.PositiveBigIntegerField(default=0)),
                ('bookmarks', models.PositiveBigIntegerField(default=0, help_text='Saves/‘watch later’.')),
                ('shares', models.PositiveBigIntegerField(default=0)),
                ('total_watch_seconds', models.PositiveBigIntegerField(default=0, help_text='Sum of watch time across users.')),
                ('avg_watch_seconds', models.FloatField(default=0.0, help_text='Rolling average watch seconds per start.')),
                ('avg_progress_pct', models.FloatField(default=0.0, help_text='Average percent completed across viewers.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('rating_count', models.PositiveBigIntegerField(default=0)),
                ('rating_sum', models.PositiveBigIntegerField(default=0, help_text='Sum of 1–5 star ratings for fast avg.')),
                ('ctr', models.DecimalField(decimal_places=4, default=0, help_text='Click-through rate; cached rollup [0–1].', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('completion_rate', models.DecimalField(decimal_places=4, default=0, help_text='Completion rate; cached rollup [0–1].', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('bounce_rate', models.DecimalField(decimal_places=4, default=0, help_text='Short-view exit fraction; cached rollup [0–1].', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('last_impressed_at', models.DateTimeField(blank=True, null=True)),
                ('last_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_interaction_at', models.DateTimeField(blank=True, null=True)),
                ('breakdown', models.JSONField(blank=True, help_text="Small cached breakdowns, e.g., {'device': {'ios': 120, 'android': 300}, 'geo': {...}}", null=True)),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['updated_at'], name='content_pla_updated_5835b0_idx'), models.Index(fields=['impressions', '-ctr'], name='content_pla_impress_0c9fc1_idx'), models.Index(fields=['completion_rate'], name='content_pla_complet_7761c5_idx'), models.Index(fields=['language', 'playlist_type'], name='content_pla_languag_cbe7fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('instructor', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Instructor')),
                ('content_genre', models.CharField(blank=True, choices=[('MEDITATION_SERIES', 'Meditation Series'), ('BREATHWORK_SERIES', 'Breathwork Series'), ('MINDFULNESS', 'Mindfulness Practices'), ('ZEN_MODE', 'Zen Mode Exclusives'), ('SLEEP_WELLNESS', 'Sleep & Relaxation'), ('STRESS_RELIEF', 'Stress Relief'), ('WEIGHT_MANAGEMENT', 'Weight Management'), ('FLEXIBILITY', 'Flexibility & Mobility'), ('STRENGTH', 'Strength Building'), ('ENERGY_BOOST', 'Energy Boost'), ('FOCUS_CONCENTRATION', 'Focus & Concentration'), ('ANXIETY_RELIEF', 'Anxiety Relief'), ('EMOTIONAL_BALANCE', 'Emotional Balance'), ('DETOX_CLEANSE', 'Detox & Cleanse'), ('IMMUNITY_SUPPORT', 'Immunity Support'), ('DAILY_CHALLENGE', 'Daily Challenge'), ('WEEKLY_PROGRAM', 'Weekly Program'), ('MONTHLY_JOURNEY', 'Monthly Journey'), ('QUICK_SESSIONS', 'Quick 5–10 min Sessions'), ('LONG_FORM_RETREAT', 'Long-form Retreat'), ('PRENATAL', 'Prenatal Yoga'), ('POSTNATAL', 'Postnatal Yoga'), ('KIDS', 'Kids Yoga & Mindfulness'), ('SENIORS', 'Senior Wellness'), ('OFFICE_BREAK', 'Office/Workplace Break'), ('TRAVEL_FRIENDLY', 'Travel-Friendly Routines'), ('TRADITIONAL_HATHA', 'Traditional Hatha Yoga'), ('VINYASA_FLOW', 'Vinyasa Flow'), ('ASHTANGA', 'Ashtanga Series'), ('BHAKTI_DEVOTIONAL', 'Bhakti/Devotional'), ('SUTRAS_MANTRAS', 'Sutras & Mantras')], help_text='Describes the genre of the content.', max_length=50, null=True, verbose_name='Content Genre')),
                ('content_type', models.CharField(blank=True, choices=[('EBOOK', 'E-Book'), ('ARTICLE', 'Article'), ('BLOG', 'Blog'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('PODCAST', 'Podcast'), ('GUIDE', 'Guide / Handbook'), ('RESEARCH_PAPER', 'Research Paper')], help_text='Describes the form of the content.', max_length=50, null=True, verbose_name='Content Type')),
                ('language', models.CharField(choices=[('ENGLISH', 'English'), ('SPANISH', 'Spanish'), ('FRENCH', 'French'), ('GERMAN', 'German'), ('ITALIAN', 'Italian'), ('PORTUGUESE', 'Portuguese'), ('RUSSIAN', 'Russian'), ('CHINESE_SIMPLIFIED', 'Chinese (Simplified)'), ('CHINESE_TRADITIONAL', 'Chinese (Traditional)'), ('JAPANESE', 'Japanese'), ('KOREAN', 'Korean'), ('ARABIC', 'Arabic'), ('TURKISH', 'Turkish'), ('DUTCH', 'Dutch'), ('SWEDISH', 'Swedish'), ('NORWEGIAN', 'Norwegian'), ('DANISH', 'Danish'), ('GREEK', 'Greek'), ('HEBREW', 'Hebrew'), ('POLISH', 'Polish'), ('UKRAINIAN', 'Ukrainian'), ('THAI', 'Thai'), ('VIETNAMESE', 'Vietnamese'), ('INDONESIAN', 'Indonesian'), ('MALAY', 'Malay'), ('FILIPINO', 'Filipino'), ('HINDI', 'Hindi'), ('BENGALI', 'Bengali'), ('PUNJABI', 'Punjabi'), ('MARATHI', 'Marathi'), ('GUJARATI', 'Gujarati'), ('TAMIL', 'Tamil'), ('TELUGU', 'Telugu'), ('KANNADA', 'Kannada'), ('MALAYALAM', 'Malayalam'), ('ODIA', 'Odia'), ('ASSAMESE', 'Assamese'), ('URDU', 'Urdu'), ('SANSKRIT', 'Sanskrit')], default='ENGLISH', help_text='Primary language of the content.', max_length=50, verbose_name='Language')),
                ('difficulty_level', models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('ALL_LEVELS', 'All Levels')], help_text='Indicates the difficulty level of the content.', max_length=50, null=True, verbose_name='Difficulty Level')),
                ('video', models.FileField(blank=True, max_length=1000, null=True, storage=utilities.storages.ImageKitStorage(), upload_to='content/videos', verbose_name='Video File')),
                ('video_file_id', models.CharField(blank=True, editable=False, max_length=1000, null=True, verbose_name='Video File ID')),
                ('thumbnail', models.ImageField(blank=True, max_length=1000, null=True, storage=utilities.storages.ImageKitStorage(), upload_to='content/videos/thumbnails', verbose_name='Thumbnail')),
                ('thumbnail_file_id', models.CharField(blank=True, editable=False, max_length=1000, null=True, verbose_name='Thumbnail File ID')),
                ('subtitles', models.FileField(blank=True, max_length=1000, null=True, storage=utilities.storages.ImageKitStorage(), upload_to='content/videos/subtitles', verbose_name='Subtitles')),
                ('subtitles_file_id', models.CharField(blank=True, editable=False, max_length=1000, null=True, verbose_name='Subtitles File ID')),
                ('transcript', models.FileField(blank=True, max_length=1000, null=True, storage=utilities.storages.ImageKitStorage(), upload_to='content/videos/transcripts', verbose_name='Transcript')),
                ('transcript_file_id', models.CharField(blank=True, editable=False, max_length=1000, null=True, verbose_name='Transcript File ID')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (seconds)')),
                ('hls_manifest_url', models.URLField(blank=True, null=True, verbose_name='HLS Manifest URL')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('publish_at', models.DateTimeField(blank=True, null=True, verbose_name='Publish At')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('requires_subscription', models.BooleanField(default=False, verbose_name='Requires Subscription')),
                ('zen_mode_only', models.BooleanField(default=False, verbose_name='Zen Mode Only')),
                ('ai_pose_model_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='AI Pose Model Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('playlist', models.ManyToManyField(blank=True, related_name='videos', to='content.playlist')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
