# Generated by Django 5.1.11 on 2026-05-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_category_dailytip_deal_recipe_session_userdailystat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbientSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('emoji', models.CharField(max_length=10, verbose_name='Emoji')),
                ('color_hex', models.CharField(default='#4A7C59', max_length=9, verbose_name='Color Hex')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Ambient Sound',
                'verbose_name_plural': 'Ambient Sounds',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BreathworkExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('pattern', models.CharField(max_length=100, verbose_name='Pattern')),
                ('duration', models.CharField(max_length=50, verbose_name='Duration')),
                ('color_hex', models.CharField(default='#4A7C59', max_length=9, verbose_name='Color Hex')),
                ('icon_name', models.CharField(default='Air', max_length=100, verbose_name='Icon Name')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Breathwork Exercise',
                'verbose_name_plural': 'Breathwork Exercises',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popular_searches', models.JSONField(default=list, verbose_name='Popular Searches')),
                ('filter_chips', models.JSONField(default=list, verbose_name='Filter Chips')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Search Configuration',
                'verbose_name_plural': 'Search Configurations',
            },
        ),
    ]
