# Generated by Django 5.1.11 on 2026-05-04 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_ambientsound_breathworkexercise_searchconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userplanitem',
            name='content_use_user_id_4a010e_idx',
        ),
        migrations.AddIndex(
            model_name='userplanitem',
            index=models.Index(fields=['user', 'date', 'is_done'], name='planitem_user_date_done_idx'),
        ),
    ]
