# Generated by Django 5.1.11 on 2026-05-09 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_add_planitem_user_date_done_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['expires_at'], name='deal_expires_at_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['playlist_type'], name='playlist_type_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['language'], name='playlist_language_idx'),
        ),
        migrations.AddIndex(
            model_name='userplanitem',
            index=models.Index(fields=['user', 'session'], name='planitem_user_session_idx'),
        ),
    ]
