# Generated by Django 5.1.11 on 2026-04-07 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otp',
        ),
    ]
