# Generated by Django 5.1.11 on 2026-04-12 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='last_consolidation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='long_term',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='memory',
            name='sessions_since_consolidation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memory',
            name='short_term',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='memory',
            name='user_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='memory',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='memory',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory', to=settings.AUTH_USER_MODEL),
        ),
    ]
