# Generated by Django 5.1.11 on 2026-05-09 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0004_chatsession_chatmessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', '-created_at'], name='idx_chatmsg_sess_ts_desc'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(condition=models.Q(('is_archived', False)), fields=['user', '-updated_at'], name='idx_active_sessions'),
        ),
    ]
