# Generated by Django 5.1.11 on 2026-05-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0005_chatmessage_idx_chatmsg_sess_ts_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
